### ISSUE TITLE
Sensor hookup with board with i2c

### ISSUE THREAD

**Issue by bnjroos** [arraym/LIS2DW12-Arduino-Lib#1]
Hi,

I am trying to use your library with an esp32 over I2C however I only get values of accel at 0 and temperature is always at 25C. I think it might fail because of my setup. I am using a https://www.st.com/en/evaluation-tools/steval-mki179v1.html board, I can see the device with i2c scan at address 0x19. I've tried to hook it up as per datasheet (10k ohm pullups etc. and CS tied to VDDIO) without success.

Would you mind sharing your setup ?

Thank you,

Bnj

EDIT: I have tried over SPI, it seems to work.

**Comment by bnjroos** [comment]
Working great with SPI, I'll stick with SPI for now.
For people using ESP32, the tap interrupt code won't work out of the box, it requires to modify it for esp32 as the interrupts do not work the same as classic arduino.

**Comment by itsuhhhlan** [comment]
@bnjroos how did you get it to work over SPI? I'm getting values that don't make any sense using the minimalistexample
